version: '3.9'
services:
  postgres:
    container_name: HR_Forecast_postgres
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5432:5432'
    restart: unless-stopped
